packages:
  - packages/*
  - packages/actor-scraper/*

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@apify/*"
  - "@crawlee/*"
  - "apify-client"
  - "apify"
  - "crawlee"
  - "got-scraping"

onlyBuiltDependencies:
  - "@playwright/browser-chromium"
  - "@swc/core"
  - camoufox-js
  - esbuild
  - playwright
  - puppeteer

nodeLinker: hoisted
linkWorkspacePackages: true
preferWorkspacePackages: true
